[Add Problem] Many Factorials
yosupo06/library-checker-problems pull request #1062
Opened 2023-11-13 16:00 UTC by suisen-cp

$`10 ^ 5`$ クエリで作りました。実行時間 (手元の環境で計測) は以下の通りで、解法の区別は出来ていそうです。

- 想定解: 0.55 sec
- $`{} _ n P _ r`$ クエリの $`r`$ を 2 冪に分解して $`\log P`$ 回 multieval
  - 高速な multieval: 1.3 sec
  - 通常の multieval: 2.0 sec
- $`\langle O(\sqrt{P}\log P), O(\sqrt{P}) \rangle`$: 3.7 sec
- naive: TLE

2023-11-16 10:33 UTC, maspypy commented
クエリ先読みソート → 愚直O(mod+T)
というのが 3.1sec くらい（真ん中で切って mod/2 にするとその半分）。AC するだけならこれが一番簡単な気がする。

2023-11-16 10:39 UTC, maspypy approved these changes

2023-11-21 18:01 UTC, NachiaVivias requested changes

2023-11-21 18:01 UTC, NachiaVivias commented on math/many_factorials/task.md
> +- $1\leq T\leq @{param.TMAX}$
```suggestion
- $1\leq T\leq @{param.T_MAX}$
```

2023-11-21 18:56 UTC, NachiaVivias approved these changes

2023-11-21 18:57 UTC, NachiaVivias commented
作業ありがとうございました。マージします。

2023-11-21 18:57 UTC, merged