問題追加 Minimum Spanning Tree
yosupo06/library-checker-problems pull request #1073
Opened 2023-12-20 10:54 UTC by kzrnm

resolve #953

directedmst をベースに自己ループ、多重辺を出力するようにしました。
correct.cpp は Prim 法で実装してます。

テストケースは適当に思いついたものを入れてます。

2023-12-21 04:52 UTC, maspypy commented on graph/minimum_spanning_tree/checker.cpp
> +        int ei = stream.readInt(0, m);
readInt(0, m-1) だと思います

2023-12-21 04:52 UTC, maspypy commented on graph/minimum_spanning_tree/task.md
> +- @{lang.en} The given graph is connected. @{lang.ja} 与えられるグラフは連結 @{lang.end}
リストの一部に lang を使うと壊れるという仕様がありまして、お手数ですが次のようにしてください。

```
@{lang.en} 

- $1 \leq N \leq @{param.N_MAX}$
- $N - 1 \leq M \leq @{param.N_MAX}$
- $0 \leq a_i, b_i < N$
- $0 \leq c_i \leq @{param.C_MAX}$
- The given graph is connected. 

@{lang.ja}

- $1 \leq N \leq @{param.N_MAX}$
- $N - 1 \leq M \leq @{param.N_MAX}$
- $0 \leq a_i, b_i < N$
- $0 \leq c_i \leq @{param.C_MAX}$
- 与えられるグラフは連結

@{lang.end}
```

2023-12-21 12:32 UTC, maspypy approved these changes

2023-12-24 05:43 UTC, NachiaVivias requested changes

2023-12-24 05:43 UTC, NachiaVivias commented on graph/minimum_spanning_tree/task.md
> +$e_0$ $e_1$ $e_2$ ... $e_{N - 1}$
```suggestion
$e_0$ $e_1$ $e_2$ ... $e_{N - 2}$
```

2023-12-24 05:43 UTC, NachiaVivias commented on graph/minimum_spanning_tree/task.md
> +Given a weighted undirected graph with $N$ vertices and $M$ edges. $i$-th edge is $(a_i, b_i)$ and has a weight of $c_i$. This graph may not be simple.
```suggestion
Given a weighted undirected graph with $N$ vertices and $M$ edges. The $i$-th edge is $(a_i, b_i)$ and has a weight of $c_i$. This graph may not be simple.
```

2023-12-24 08:40 UTC, NachiaVivias approved these changes
変更確認しました。

2023-12-24 09:47 UTC, maspypy commented
ありがとうございます、マージします。

2023-12-24 09:48 UTC, merged