問題追加 static_range_mode_query
yosupo06/library-checker-problems pull request #1077
Opened 2024-01-02 04:22 UTC by maspypy

つくりました

2024-01-02 04:24 UTC, maspypy commented
gen はほとんど static_range_count_distinct そのままです（$l=r$ が作られないようにしただけ）。

2024-01-17 13:15 UTC, tko919 requested changes

2024-01-17 13:15 UTC, tko919 commented on datastructure/static_range_mode_query/task.md
> +- $0 \leq l \lt \leq N$
0 \leq l \lt r \leq N

2024-01-17 17:07 UTC, maspypy commented on datastructure/static_range_mode_query/task.md
> +- $0 \leq l \lt \leq N$
ありがとうございます、なおしました

2024-01-17 20:36 UTC, tko919 approved these changes

2024-01-18 03:25 UTC, maspypy commented
マージします。

2024-01-18 03:25 UTC, merged