問題追加 Counting Square-free Integers
yosupo06/library-checker-problems pull request #1103
Opened 2024-01-27 20:48 UTC by tko919

#1102

2024-01-28 10:12 UTC, NachiaVivias requested changes

2024-01-28 10:12 UTC, NachiaVivias commented on math/counting_squarefrees/info.toml
> +title = 'Counting Square-free integers'
```suggestion
title = 'Counting Square-free Integers'
```

2024-01-29 14:01 UTC, NachiaVivias approved these changes

2024-01-30 06:32 UTC, maspypy commented on math/counting_squarefrees/info.toml
> +timelimit = 5.0
writer 解が 1700ms くらいっぽいし、TL 10.0 でもいい気がします。

2024-01-30 06:32 UTC, maspypy commented on math/counting_squarefrees/task.md
> +Count the number of square-free integers no more than $N$.
英語よくわからないですが、codeforces 問題文だと「not greater than」となっていることがほとんどなので、競プロ文化だとその方が一般的かもしれません

2024-01-30 18:47 UTC, tko919 commented
Counting Primesの方の問題文も修正しました。

2024-01-30 19:19 UTC, maspypy approved these changes

2024-01-30 19:20 UTC, maspypy commented
ありがとうございます、マージします

2024-01-30 19:20 UTC, merged