問題追加 matrix_product_mod_2
yosupo06/library-checker-problems pull request #1108
Opened 2024-02-10 17:17 UTC by maspypy

つくりました

2024-02-10 17:19 UTC, maspypy commented
#896

2024-02-10 17:21 UTC, maspypy commented
入出力が結構大きいので、文字列にしました。あとは大体 mod 998 と同じです。

2024-02-11 06:35 UTC, suisen-cp requested changes

2024-02-11 06:35 UTC, suisen-cp commented on math/matrix_product_mod_2/sol/correct.cpp
> +char BUF[MAX];
`\0` の分を含めて `char BUF[MAX + 1];` と宣言する必要がありそうです (naive.cpp も同様)

2024-02-11 09:20 UTC, maspypy commented
ありがとうございます、なおしました。

2024-02-12 02:57 UTC, suisen-cp approved these changes

2024-02-13 11:36 UTC, maspypy commented
ありがとうございます、マージします

2024-02-13 11:36 UTC, merged