問題追加 Rational Approximation
yosupo06/library-checker-problems pull request #1110
Opened 2024-02-23 15:51 UTC by lpha-z

問題案 #960 を実装しました。

2024-02-25 12:03 UTC, maspypy commented on math/rational_approximation/task.md
> +$vdots$
\vdots

2024-02-25 12:03 UTC, maspypy commented on math/rational_approximation/task.md
> +$S$ に含まれる元のうち、 $x/y$ 以上であるものの最小値（存在しない場合は$0/1$）および $x/y$ 以下であるものの最大値（存在しない場合は$1/0$）を求めてください。
それぞれ
$x/y$ 以下であるものの最大値（存在しない場合は $0/1$）
$x/y$ 以上であるものの最小値（存在しない場合は $1/0$）
だと思います。（英語も同様）

2024-02-27 12:23 UTC, maspypy approved these changes

2024-02-27 12:45 UTC, lpha-z commented
レビューとapproveありがとうございます。

2024-03-19 08:40 UTC, maspypy commented
新しい問題は、problems admin が 2 人 approve してからマージするという運用をしているのでお待ちください。

2024-03-19 08:41 UTC, NachiaVivias requested changes

2024-03-19 08:41 UTC, NachiaVivias commented on math/rational_approximation/task.md
> +$a b c d$
```suggestion
$a$ $b$ $c$ $d$
```

2024-03-19 08:41 UTC, NachiaVivias commented on math/rational_approximation/task.md
> +$N_{T-1} x_{T-1} y_{T-1}$
```suggestion
$N_0$ $x_0$ $y_0$
$N_1$ $x_1$ $y_1$
$\vdots$
$N_{T-1}$ $x_{T-1}$ $y_{T-1}$
```

2024-03-19 08:41 UTC, NachiaVivias commented on math/rational_approximation/task.md
> +Determine the maximum value in $S$ that is less than or equal to $x/y$ ($0/1$ if not exist) and the minimum value in $S$ that is greater than $x/y$ ($1/0$ if not exist).
```suggestion
Determine the maximum value in $S$ that is less than or equal to $x/y$ ($0/1$ if not exist) and the minimum value in $S$ that is greater than or equal to $x/y$ ($1/0$ if not exist).
```

2024-03-19 11:55 UTC, lpha-z commented
三件の指摘ありがとうございます、受け入れました

2024-03-19 12:40 UTC, maspypy commented
Unittest(C++ lib) / util-test (pull_request) 

はいまなんか確率（結構高い）で落ちるみたい（運営で共有済）なので、適当に re run したりしてみます。

2024-03-19 15:22 UTC, NachiaVivias approved these changes
確認しました。ありがとうございます。

2024-03-19 15:31 UTC, maspypy commented
ありがとうございます、マージします。

2024-03-19 15:31 UTC, merged