問題追加 compositonal_inverse (Large)
yosupo06/library-checker-problems pull request #1114
Opened 2024-03-18 19:57 UTC by maspypy

2024-03-18 19:57 UTC, maspypy commented
https://github.com/yosupo06/library-checker-problems/issues/1112

2024-03-19 07:22 UTC, NachiaVivias requested changes

2024-03-19 07:22 UTC, NachiaVivias commented on math/compositional_inverse_of_formal_power_series_large/task.md
> +- $2 \leq N \leq 8000$
```suggestion
- $2 \leq N \leq @{param.N_MAX}$
```

2024-03-19 07:56 UTC, NachiaVivias approved these changes

2024-03-19 08:38 UTC, maspypy commented
こっちも check 通った。マージしてしまうか。
review ありがとうございました。

2024-03-19 08:38 UTC, merged