問題追加 Counting Spanning Tree
yosupo06/library-checker-problems pull request #1163
Opened 2024-05-20 20:15 UTC by maspypy

つくりました。無向・有向で 2 問あります。example 以外はランダムケースしかないけどまあ大丈夫かなと思っています。

2024-05-20 20:16 UTC, maspypy commented
https://github.com/yosupo06/library-checker-problems/issues/1082

2024-06-02 10:27 UTC, NachiaVivias requested changes

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_directed/task.md
> +Find the number of directed spanning tree whose root is the vertex $r$ (it means that all the verties have to be reachable from $r$), modulo $998244353$.
```suggestion
Find the number of directed spanning trees whose root is the vertex $r$ (it means that all the vertices have to be reachable from $r$), modulo $998244353$. 
```

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_undirected/task.md
> +Find the number of spanning tree of the graph modulo $998244353$.
```suggestion
Find the number of spanning trees of the graph modulo $998244353$. 
```

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_undirected/info.toml
> +title = 'Counting Spanning Tree (Undirected)'
```suggestion
title = 'Counting Spanning Trees (Undirected)'
```

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_directed/info.toml
> +title = 'Counting Spanning Tree (Directed)'
```suggestion
title = 'Counting Spanning Trees (Directed)'
```

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_directed/gen/random.cpp
> +  int M = gen.uniform<int>(0, M_MAX);
```suggestion
  int N = gen.uniform<int>(N_MIN, N_MAX);
  int M = gen.uniform<int>(M_MIN, M_MAX);
```

2024-06-02 10:27 UTC, NachiaVivias commented on graph/counting_spanning_tree_undirected/gen/random.cpp
> +  int M = gen.uniform<int>(0, M_MAX);
```suggestion
  int N = gen.uniform<int>(N_MIN, N_MAX);
  int M = gen.uniform<int>(M_MIN, M_MAX);
```

2024-06-02 10:33 UTC, NachiaVivias commented
テストケースジェネレータに標準入出力のライブラリが include していないように見えます。もっと気にするなら `atoll` のための `<cstdlib>` がもしかしたら必要かもしれません。

2024-06-02 11:02 UTC, maspypy commented
ありがとうございます。

include 関係については、手元で正常に実行できて、push したあとのテストも上手くいけば OK。
と処理していたのですが、これだと手順が足りていないですか？

2024-06-02 11:15 UTC, NachiaVivias commented
> include 関係については、手元で正常に実行できて、push したあとのテストも上手くいけば OK。

その雰囲気でよいとも考えますが、 `<cstdint>` の不足とかでは後から問題になったこともあるので、私は、気づいたらラッキーくらいには見ています。

ところで、今回は入出力系が include されていないのに通っているというように見えて、これ系では特に強い違和感がありますが、入れておきませんか？

2024-06-02 11:23 UTC, maspypy commented
念のためという感じですかね。ありがとうございます。
検索してみたら printf, scanf は cstdio, atoll は cstdlib というのは確かに出てきたので、入れました。

2024-06-02 14:36 UTC, NachiaVivias approved these changes

2024-06-02 14:37 UTC, NachiaVivias commented
ありがとうございます。

2024-06-02 18:39 UTC, maspypy commented
ありがとうございます、マージします。

2024-06-02 18:39 UTC, merged