問題追加 Range Parallel Unionfind
yosupo06/library-checker-problems pull request #1189
Opened 2024-06-11 18:52 UTC by maspypy

つくりました

2024-06-11 18:53 UTC, maspypy commented
https://github.com/yosupo06/library-checker-problems/issues/934

2024-06-12 07:32 UTC, NachiaVivias commented
初期状態で $X=\sum x _ i$ になっているようですが、意図通りですか？

2024-06-12 07:33 UTC, maspypy commented
あれ、変ですね。なおします。

2024-06-12 07:36 UTC, maspypy commented
なおしました。

2024-06-12 08:18 UTC, NachiaVivias requested changes

2024-06-12 08:18 UTC, NachiaVivias commented on datastructure/range_parallel_unionfind/info.toml
> +    number = 3
ジェネレータのソースコードには 4 ケース分定義されていて、一致しません。

2024-06-12 08:29 UTC, maspypy commented
ありがとうございます、なおしました。

2024-06-12 08:32 UTC, NachiaVivias approved these changes
対応ありがとうございます。

2024-06-12 08:33 UTC, merged