問題追加 bell number
yosupo06/library-checker-problems pull request #1274
Opened 2024-11-04 14:23 UTC by maspypy

つくりました

2024-11-04 14:23 UTC, maspypy commented
https://github.com/yosupo06/library-checker-problems/issues/716

2024-11-11 17:19 UTC, NachiaVivias requested changes

2024-11-11 17:19 UTC, NachiaVivias commented on enumerative_combinatorics/bell_number/task.md
> +The number of ways to partition a set of n elements into non-empty subsets is called the Bell number $B_n$.
```suggestion
The number of ways to partition a set of $n$ elements into non-empty subsets is called the Bell number $B_n$. 
```

2024-11-11 18:10 UTC, NachiaVivias approved these changes

2024-11-11 18:13 UTC, merged