[Add Problem] Vertex Get Range Contour Add on Tree
yosupo06/library-checker-problems pull request #972
Opened 2023-04-29 11:22 UTC by suisen-cp

#831 

テストケースは #816 のものを流用しました。

2023-05-05 06:55 UTC, NachiaVivias requested changes

2023-05-11 11:20 UTC, suisen-cp commented on graph/vertex_get_range_contour_add_on_tree/gen/random_small_tree_many_query_1.cpp
> +    const int n = gen.uniform(int(N_MIN), 10), q = Q_MAX;
罠になりそうな木の形状が思い浮かばない (& 重心分解の終端近くである程度小さい木に対する動作もチェックできていそう？) ので、一旦 n(=1,2,...,10) だけ固定して形状はランダムにします

2023-05-11 14:54 UTC, suisen-cp commented
指摘いただいた部分を修正しました

2023-05-18 13:05 UTC, maspypy approved these changes

2023-05-18 13:05 UTC, maspypy commented
マージします。

2023-05-18 13:05 UTC, merged